### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

###
GET http://localhost:8080/funcionarios/4dc90e56-230c-47c5-a70f-39532fcf1f4a

###

###
POST http://localhost:8080/funcionarios
Content-Type: application/json

{
  "nome": "sr R",
  "papel": "Artista"
}

###

###
PUT http://localhost:8080/funcionarios/4dc90e56-230c-47c5-a70f-39532fcf1f4a
Content-Type: application/json

{
  "nome": "sr Rafinha",
  "papel": "desenvolvedor"
}

###

###
DELETE http://localhost:8080/funcionarios/3

###