### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###


###
POST http://localhost:8080/order
Content-Type: application/json

{
"description": "Teclado",
"status":      "IN_PROGRESS"
}
###

###
GET http://localhost:8080/orders
###

###
GET http://localhost:8080/order/204
###

###
PUT http://localhost:8080/orders/204/complete
###

###
PUT http://localhost:8080/orders/204/rollbackStatus
###

###
DELETE http://localhost:8080/order/204/cancel
###